### ISSUE TITLE
For Instagram rounded button  class is  only Instagram and For Square button class is Instagram-rounded this should be changed

### ISSUE THREAD

**Issue by dsnehasish74** [shahednasser/sbuttons#271]
![Screenshot (162)_LI](https://user-images.githubusercontent.com/58779604/94371873-421cee80-0117-11eb-9188-25881a50474a.jpg)
![Screenshot (162)_LI](https://user-images.githubusercontent.com/58779604/94371879-52cd6480-0117-11eb-9aa2-ab63719d71bb.jpg)

**Describe the bug**

**Expected behavior of what should have happened (if applicable)**

**Screenshots (if applicable)**

**Additional notes**

**Comment by dsnehasish74** [comment]
Can I fix this bug

**Comment by dsnehasish74** [comment]
#272

**Comment by shahednasser** [comment]
I agree with what you are saying, but I think the better solution is to keep it consistent throughout the website. Usually, we just added the class `rounded-btn` to any button type to make it rounded instead of adding a new class relating to that button (for example, `instagram-rounded`)

I think what we need to do is remove all the "rounded" classes for the social buttons (instagram-rounded, facebook-rounded, etc....) and just add to these buttons `rounded-btn`. This will also help us display the buttons in the same manner as previous buttons. 

Let me know if you can work on this (in a different PR than the one you submitted).

**Comment by Neeraj3508** [comment]
I can work if you want
